#!/bin/sh
# Pre-commit hook: run the same gates as CI, in CONTRIBUTING.md order.
# Install with: ln -sf ../../scripts/pre-commit .git/hooks/pre-commit
set -e

cd "$(git rev-parse --show-toplevel)"
make fmt lint test
