// Package render turns untrusted repo content into safe HTML for the browse UI:
// syntax-highlighted source (chroma) and rendered markdown (goldmark). It is
// deliberately separate from webui so the security-critical rendering — every
// byte here originates from a repo and is shown to an admin — is unit-testable
// in isolation.
//
// Two defenses guard the markdown path (task 15 safety): goldmark escapes raw
// HTML by default (WithUnsafe is never set), and bluemonday's UGCPolicy strips
// what slips through — scripts, event-handler attributes, and javascript:/data:
// URLs. chroma's class-based output is static markup (no scripts) and its
// stylesheet is generated, not repo-derived, so both are safe to embed.
package render

import (
	"bytes"
	"html/template"
	"path"
	"strings"
	"sync"

	chromahtml "github.com/alecthomas/chroma/v2/formatters/html"
	"github.com/alecthomas/chroma/v2/lexers"
	"github.com/alecthomas/chroma/v2/styles"
	"github.com/microcosm-cc/bluemonday"
	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/extension"

	highlighting "github.com/yuin/goldmark-highlighting/v2"
	mermaid "go.abhg.dev/goldmark/mermaid"
)

// MaxSize caps the input render will highlight or markdown-render. Above it the
// caller falls back to a plain <pre>: a minified or generated blob shouldn't
// turn into pathological HTML.
const MaxSize = 512 * 1024

// highlightStyle is the chroma theme shared by blob view and README code
// blocks, so the two match. Class-based output pairs it with HighlightCSS.
// darkStyle is its dark-mode counterpart, emitted under a prefers-color-scheme
// media query — same class names, so it overrides when the viewer's OS is dark.
var (
	highlightStyle = styles.Get("github")
	darkStyle      = styles.Get("github-dark")
)

// classFormatter emits class-based (not inline-style) highlight markup, so a
// single stylesheet from HighlightCSS covers every page.
var classFormatter = chromahtml.New(chromahtml.WithClasses(true), chromahtml.TabWidth(4))

// Highlight renders code as syntax-highlighted, class-based HTML wrapped in the
// formatter's <pre>. The lexer is chosen by filename, then by content analysis,
// then plain text. Highlighting is best-effort: on any lexer/format error the
// caller falls back to a plain <pre>.
func Highlight(code []byte, filename string) (template.HTML, error) {
	lexer := lexers.Match(path.Base(filename))
	if lexer == nil {
		lexer = lexers.Analyse(string(code))
	}
	if lexer == nil {
		lexer = lexers.Fallback
	}
	it, err := lexer.Tokenise(nil, string(code))
	if err != nil {
		return "", err
	}
	var buf bytes.Buffer
	if err := classFormatter.Format(&buf, highlightStyle, it); err != nil {
		return "", err
	}
	return template.HTML(buf.String()), nil //nolint:gosec // chroma class output is static markup
}

var highlightCSS struct {
	sync.Once
	css template.CSS
}

// HighlightCSS is the stylesheet paired with Highlight's class-based output, for
// the layout to include once. It is generated by chroma from a fixed theme —
// trusted, not repo-derived — and cached after the first build.
func HighlightCSS() template.CSS {
	highlightCSS.Do(func() {
		var buf bytes.Buffer
		_ = classFormatter.WriteCSS(&buf, highlightStyle)
		// The dark theme reuses the same classes, wrapped in a media query so it
		// only takes effect when the viewer's OS is in dark mode.
		buf.WriteString("@media (prefers-color-scheme: dark) {\n")
		_ = classFormatter.WriteCSS(&buf, darkStyle)
		buf.WriteString("}\n")
		highlightCSS.css = template.CSS(buf.String())
	})
	return highlightCSS.css
}

// markdown renders CommonMark + GFM. Raw HTML is escaped (goldmark's default,
// WithUnsafe intentionally unset); fenced code is routed through chroma with the
// same class-based theme as blob view.
var markdown = goldmark.New(
	goldmark.WithExtensions(
		extension.GFM,
		highlighting.NewHighlighting(
			highlighting.WithFormatOptions(chromahtml.WithClasses(true)),
		),
		// A ```mermaid fence becomes <pre class="mermaid">…escaped source…</pre>
		// for client-side rendering (bluemonday passes the class we already allow on
		// <pre>). RenderModeClient is explicit so a stray `mmdc` on PATH can't flip
		// us to server-side; NoScript because we include our own embedded, trusted
		// mermaid.js from the layout — the extension's CDN <script> would be stripped
		// by the sanitizer anyway.
		&mermaid.Extender{RenderMode: mermaid.RenderModeClient, NoScript: true},
	),
)

// sanitizer strips dangerous constructs goldmark passes through, while allowing
// the class attribute chroma needs on the code elements it emits (so README
// code stays highlighted). UGCPolicy already forbids scripts, event handlers,
// and javascript:/data: URL schemes.
var sanitizer = func() *bluemonday.Policy {
	p := bluemonday.UGCPolicy()
	p.AllowAttrs("class").OnElements("div", "pre", "code", "span")
	return p
}()

// Markdown renders src to sanitized HTML. It never returns unsafe markup: even
// if goldmark errored, the (empty) output passes through the sanitizer.
func Markdown(src []byte) template.HTML {
	var buf bytes.Buffer
	if err := markdown.Convert(src, &buf); err != nil {
		return ""
	}
	return template.HTML(sanitizer.SanitizeBytes(buf.Bytes())) //nolint:gosec // sanitized above
}

// HasMermaid reports whether rendered markdown contains a mermaid diagram block
// (emitted as <pre class="mermaid">), so a page pulls in the mermaid script only
// when it actually has a diagram. Repo text that literally reads class="mermaid"
// is HTML-escaped by the renderer, so it can't trip this.
func HasMermaid(h template.HTML) bool {
	return strings.Contains(string(h), `class="mermaid"`)
}

// IsMarkdown reports whether filename names a markdown file (.md/.markdown,
// case-insensitive).
func IsMarkdown(filename string) bool {
	switch strings.ToLower(path.Ext(filename)) {
	case ".md", ".markdown":
		return true
	default:
		return false
	}
}

// IsReadme reports whether name is a README markdown file (README.md /
// README.markdown, case-insensitive) — the file rendered below a tree listing.
func IsReadme(name string) bool {
	lower := strings.ToLower(name)
	return lower == "readme.md" || lower == "readme.markdown"
}
